[package]
name = "cga2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
bitflags = "2.6.0"
itertools = "0.12.1"
